mongodb:
  image: mongo:3.2
  container_name: vote-mongodb
  expose:
    - 27017/tcp

auth:
  build: .
  command: python3 /home/application/server.py
  container_name: vote-service
  volumes:
    - ./src/:/home/application/
  links:
    - mongodb
  ports:
    - "8060:8060"
  environment:
    MONGODB_SERVER_HOST: 'votw-mongodb'
    MONGODB_SERVER_PORT : '27017'
    MONGODB_DB_NAME : 'vote-for-number'
    SERVER_HOST : '0.0.0.0'
    SERVER_PORT : '8060'